# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swastika' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Swastika
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  
  pod 'React', path: '../node_modules/react-native', :subspecs => [    
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'BatchedBridge',
      'DevSupport'
  ]    
  #pod 'GooglePlaces'
  # pod 'GooglePlacePicker'
  # pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS
  # pod 'react-native-maps', path: '../node_modules/react-native-maps/'
  # pod 'react-native-google-maps', path: '../node_modules/react-native-maps/'  # <~~ if you need GoogleMaps support on iOS
end
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#       if target.name == "react-native-google-maps"
#           target.build_configurations.each do |config|
#               config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
#           end
#       end
#   end
# end
post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == 'yoga'
          target.build_configurations.each do |config|
              config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          end
      end
  end
end

target 'Swastika-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Swastika-tvOS

  target 'Swastika-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
